org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
systemProp.java.net.preferIPv4Stack=true
systemProp.java.net.preferIPv4Addresses=true
systemProp.java.net.preferIPv6Addresses=false
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.java.home=/home/cslh/smart-sales/android-smart-sales/SmartSalesAssistant_Final_Delivery/jdk-17.0.9+9
org.gradle.daemon=false
